### PR TITLE
Edited control-bar.js.

### PR DESCRIPTION
**Pull request by mouthzipper**
Edited control-bar.js  to hide volume control and mute toggle in ios and android devices.

### CODE REVIEW

**Comment by sydcanem** [comment]
@mouthzipper html5.js line 256 from:

```
vjs.Html5.canControlVolume = function(){
   var volume =  vjs.TEST_VID.volume;
   vjs.TEST_VID.volume = (volume / 2) + 0.1;
   return volume !== vjs.TEST_VID.volume;
};
```

to 

```
 vjs.Html5.canControlVolume = function(){
    var volume =  vjs.TEST_VID.volume;
    vjs.TEST_VID.volume = (volume / 2) + 0.1;
    // iOS can't control volume but Android can
    // but we also have to remove it on Android
    return volume !== vjs.TEST_VID.volume && !vjs.IS_ANDROID;
};
```

**Comment by sydcanem** [comment]
also run tests before merging :)

**Comment by sydcanem** [comment]
If android will use Flash ( I doubt it will ) volume will still appear. Only HTML5 players on android will not display volume control.

**Comment by mouthzipper** [comment]
thanks @sydcanem . it worked well when I test. :+1:

**Pull request merged**
